core:
  - changed-files:
      - any-glob-to-any-file: "src/**/*"

github:
  - changed-files:
      - any-glob-to-any-file: .github/*

docs:
  - changed-files:
      - any-glob-to-any-file: README.md

docker:
  - changed-files:
      - any-glob-to-any-file: Dockerfile

dependence:
  - changed-files:
      - any-glob-to-any-file: package.json
