documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

core:
  - changed-files:
      - any-glob-to-any-file: "src/**/*"

login:
  - changed-files:
      - any-glob-to-any-file: "src/pages/login/*"
