name: Auto Label by Commit Message

on: [pull_request_target]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message and add label
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
