name: Auto Label by Commit Message

on:
  push:
    branches:
      - main

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message and add label
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commits = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });

            const commitMessage = commits.data[0].commit.message;
            console.log('Commit message:', commitMessage);

            if (commitMessage.includes('fix')) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['bug']
              });
            } else if (commitMessage.includes('feat')) {
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['enhancement']
              });
            }
